version: "3.9"

services:
  database: 
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
    #network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    #network_mode: host

volumes:
  pgdata:
    driver: local